"""simplified schedule relationship

Revision ID: 30b9040e5595
Revises: 17e34ab26857
Create Date: 2024-07-06 22:11:18.626065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b9040e5595'
down_revision: Union[str, None] = '17e34ab26857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber_association')
    op.drop_table('schedule_association')
    op.drop_constraint('uq_subscription_schedule_id', 'subscription', type_='unique')
    op.drop_constraint('uq_subscription_subscriber_id', 'subscription', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subscription_subscriber_id', 'subscription', ['subscriber_id'])
    op.create_unique_constraint('uq_subscription_schedule_id', 'subscription', ['schedule_id'])
    op.create_table('schedule_association',
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='fk_schedule_association_schedule_id_schedule'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.schedule_id'], name='fk_schedule_association_subscription_id_subscription'),
    sa.PrimaryKeyConstraint('schedule_id', 'subscription_id', 'id', name='pk_schedule_association')
    )
    op.create_table('subscriber_association',
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], name='fk_subscriber_association_subscriber_id_user'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.subscriber_id'], name='fk_subscriber_association_subscription_id_subscription'),
    sa.PrimaryKeyConstraint('subscriber_id', 'subscription_id', 'id', name='pk_subscriber_association')
    )
    # ### end Alembic commands ###
