"""added schedule_type property in Schedule models

Revision ID: 46a2feb6a011
Revises: 5c87f5862dc7
Create Date: 2024-09-25 12:54:51.956784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a2feb6a011'
down_revision: Union[str, None] = '5c87f5862dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    schedule_type_enum = sa.Enum('PUBLIC', 'PRIVATE', name='schedule_type')
    schedule_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('schedule', sa.Column('schedule_type', sa.Enum('PUBLIC', 'PRIVATE', name='schedule_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    schedule_type_enum = sa.Enum('PUBLIC', 'PRIVATE', name='schedule_type')
    schedule_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('schedule', 'schedule_type')
    # ### end Alembic commands ###
