"""added owner attribute for schedule model

Revision ID: 5c87f5862dc7
Revises: eee3304a6fe4
Create Date: 2024-08-07 13:41:03.568280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c87f5862dc7'
down_revision: Union[str, None] = 'eee3304a6fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_schedule_owner_id_user'), 'schedule', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_schedule_owner_id_user'), 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'owner_id')
    # ### end Alembic commands ###
