"""cascade relations added

Revision ID: 90c6a7042680
Revises: 30b9040e5595
Create Date: 2024-07-20 00:09:48.312478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c6a7042680'
down_revision: Union[str, None] = '30b9040e5595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_subscription_schedule_id_schedule', 'subscription', type_='foreignkey')
    op.drop_constraint('fk_subscription_subscriber_id_user', 'subscription', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscription_subscriber_id_user'), 'subscription', 'user', ['subscriber_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_subscription_schedule_id_schedule'), 'subscription', 'schedule', ['schedule_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_subscription_schedule_id_schedule'), 'subscription', type_='foreignkey')
    op.drop_constraint(op.f('fk_subscription_subscriber_id_user'), 'subscription', type_='foreignkey')
    op.create_foreign_key('fk_subscription_subscriber_id_user', 'subscription', 'user', ['subscriber_id'], ['id'])
    op.create_foreign_key('fk_subscription_schedule_id_schedule', 'subscription', 'schedule', ['schedule_id'], ['id'])
    # ### end Alembic commands ###
